apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: temp-nginx
  ports:
    - name: nginx-ports
      protocol: TCP
      port: 8090
      targetPort: 80
  type: LoadBalancer
