apiVersion: v1
kind: Pod
metadata:
  name: multicontainer-pod
spec:
  restartPolicy: Always
  volumes:
  - name: shared-date-logs
    persistentVolumeClaim:
      claimName: task-pv-claim
  initContainers:
  - name: ubuntu-demo
    image: ubuntu
    command:
      - "bin/sh"
      - "-c"
      - "echo welcome to k8 ubuntu inintcontainers"
  containers:
  - name: alpine
    image: alpine
    command: ["bin/sh"]
    args: ["-c", "while true; do date >> /var/log/index.html; sleep 10;done"]
    volumeMounts:
    - name: shared-date-logs
      mountPath: /var/log
    resources:
      limits:
        cpu: "0.2"
        memory: "200Mi"
      requests:
        cpu: "0.1"
        memory: "100Mi"
  - name: nginx
    image: nginx:1.20.0
    ports:
    - containerPort: 80
      hostPort: 8090
    volumeMounts:
    - name: shared-date-logs
      mountPath: /usr/share/nginx/html
    resources:
      limits:
        cpu: "0.3"
        memory: "300Mi"
      requests:
        cpu: "0.2"
        memory: "200Mi"