apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-hostpath
spec:
  storageClassName: nfs-storage
  capacity:
    storage: 1Gi  #Mi,Gi,Ti,Pi
  accessModes:
    - ReadWriteOnce  #ReadWriteMany, ReadOnlyMany
  hostPath:
    path: "/tmp/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim
spec:
  storageClassName: nfs-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi