apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  type: ClusterIP
  clusterIP: None # <-- Don't forget!!
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      name: http
      targetPort: 80